### ISSUE TITLE
"Ensure Hostname is Resolvable" task exists in both install.yml and configure.yml

### ISSUE THREAD

**Issue by exptom** [sansible/ssmtp#16]
What is the reasoning behind both install and configure tasks including the  "Ensure Hostname is Resolvable" task?
They each write slightly different content to the hosts file for the 127.0.0.1 line so it results in them overwriting each other every time my playbook is run.

**Comment by dennisconrad** [comment]
Thank you for your contribution!

**Comment by exptom** [comment]
@dennisconrad  please could you push the new version tag to ansible galaxy

**Comment by exptom** [comment]
@dennisconrad any chance of updating the available ansible galaxy versions to match the latest tag?
